CREATE TABLE [dbo].[Demo](
	[X] [varchar](50) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[X] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]