CREATE TABLE [dbo].[persons](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[Firstname] [varchar](255) NOT NULL,
	[Lastname] [varchar](255) NOT NULL,
	[Age] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]